= Enums

[[BridgeEventType]]
== BridgeEventType

++++
 Bridge Event Types.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SOCKET_CREATED]]`SOCKET_CREATED`|
+++
This event will occur when a new SockJS socket is created.
+++
|[[SOCKET_CLOSED]]`SOCKET_CLOSED`|
+++
This event will occur when a SockJS socket is closed.
+++
|[[SOCKET_IDLE]]`SOCKET_IDLE`|
+++
This event will occur when SockJS socket is on idle for longer period of time than configured.
+++
|[[SOCKET_PING]]`SOCKET_PING`|
+++
This event will occur when the last ping timestamp is updated for the SockJS socket.
+++
|[[SEND]]`SEND`|
+++
This event will occur when a message is attempted to be sent from the client to the server.
+++
|[[PUBLISH]]`PUBLISH`|
+++
This event will occur when a message is attempted to be published from the client to the server.
+++
|[[RECEIVE]]`RECEIVE`|
+++
This event will occur when a message is attempted to be delivered from the server to the client.
+++
|[[REGISTER]]`REGISTER`|
+++
This event will occur when a client attempts to register a handler.
+++
|[[UNREGISTER]]`UNREGISTER`|
+++
This event will occur when a client attempts to unregister a handler.
+++
|===

[[FetchDirection]]
== FetchDirection

++++
 Represents the fetch direction hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[FORWARD]]`FORWARD`|-
|[[REVERSE]]`REVERSE`|-
|[[UNKNOWN]]`UNKNOWN`|-
|===

[[HashAlgorithm]]
== HashAlgorithm


[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SHA512]]`SHA512`|
+++
The default algorithm for backward compatible systems.

 Should not be used for new projects as OWASP recommends stronger hashing algorithms.
+++
|[[PBKDF2]]`PBKDF2`|
+++
Stronger hashing algorithm, recommended by OWASP as of 2018.
+++
|===

[[HashSaltStyle]]
== HashSaltStyle

++++
 Password hash salt configuration.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NO_SALT]]`NO_SALT`|
+++
Password hashes are not salted
+++
|[[COLUMN]]`COLUMN`|
+++
Salt is in a separate column for each user in the database
+++
|[[EXTERNAL]]`EXTERNAL`|
+++
Salt is NOT stored in the database, but defined as external value like application preferences or so
+++
|===

[[LoggerFormat]]
== LoggerFormat

++++
 The possible out of the box formats.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DEFAULT]]`DEFAULT`|
+++
<i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>"
+++
|[[SHORT]]`SHORT`|
+++
<i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
+++
|[[TINY]]`TINY`|
+++
<i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
+++
|===

[[ResultSetConcurrency]]
== ResultSetConcurrency

++++
 Represents the resultset concurrency hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[READ_ONLY]]`READ_ONLY`|-
|[[UPDATABLE]]`UPDATABLE`|-
|===

[[ResultSetType]]
== ResultSetType

++++
 Represents the resultset type hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[FORWARD_ONLY]]`FORWARD_ONLY`|-
|[[SCROLL_INSENSITIVE]]`SCROLL_INSENSITIVE`|-
|[[SCROLL_SENSITIVE]]`SCROLL_SENSITIVE`|-
|===

[[ShiroAuthRealmType]]
== ShiroAuthRealmType

++++
 The type of the Shiro auth realm
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[PROPERTIES]]`PROPERTIES`|
+++
The realm is a Shiro properties auth provider
+++
|[[LDAP]]`LDAP`|
+++
The realm is a Shiro LDAP auth provider
+++
|===

[[TransactionIsolation]]
== TransactionIsolation

++++
 Represents a Transaction Isolation Level
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[READ_UNCOMMITTED]]`READ_UNCOMMITTED`|
+++
Implements dirty read, or isolation level 0 locking, which means that no shared locks are issued and no exclusive
 locks are honored. When this option is set, it is possible to read uncommitted or dirty data; values in the data
 can be changed and rows can appear or disappear in the data set before the end of the transaction. This is the
 least restrictive of the four isolation levels.
+++
|[[READ_COMMITTED]]`READ_COMMITTED`|
+++
Specifies that shared locks are held while the data is being read to avoid dirty reads, but the data can be changed
 before the end of the transaction, resulting in nonrepeatable reads or phantom data.
+++
|[[REPEATABLE_READ]]`REPEATABLE_READ`|
+++
Locks are placed on all data that is used in a query, preventing other users from updating the data, but new
 phantom rows can be inserted into the data set by another user and are included in later reads in the current
 transaction. Because concurrency is lower than the default isolation level, use this option only when necessary.
+++
|[[SERIALIZABLE]]`SERIALIZABLE`|
+++
Places a range lock on the data set, preventing other users from updating or inserting rows into the data set until
 the transaction is complete. This is the most restrictive of the four isolation levels. Because concurrency is
 lower, use this option only when necessary.
+++
|[[NONE]]`NONE`|
+++
For engines that support it, none isolation means that each statement would essentially be its own transaction.
+++
|===

[[Transport]]
== Transport

++++
 The available SockJS transports
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[WEBSOCKET]]`WEBSOCKET`|
+++
<a href="http://www.rfc-editor.org/rfc/rfc6455.txt">rfc 6455</a>
+++
|[[EVENT_SOURCE]]`EVENT_SOURCE`|
+++
<a href="http://dev.w3.org/html5/eventsource/">Event source</a>
+++
|[[HTML_FILE]]`HTML_FILE`|
+++
<a href="http://cometdaily.com/2007/11/18/ie-activexhtmlfile-transport-part-ii/">HtmlFile</a>.
+++
|[[JSON_P]]`JSON_P`|
+++
Slow and old fashioned <a hred="https://developer.mozilla.org/en/DOM/window.postMessage">JSONP polling</a>.
 This transport will show "busy indicator" (aka: "spinning wheel") when sending data.
+++
|[[XHR]]`XHR`|
+++
Long-polling using <a hred="https://secure.wikimedia.org/wikipedia/en/wiki/XMLHttpRequest#Cross-domain_requests">cross domain XHR</a>
+++
|===

